website/mainPage/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "mainPage"
urlpatterns = [
    path('', views.index, name = 'index'),
    path('events/', views.events, name = 'events'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainPage.urls')),
]

website/mainPage/models.py
from django.db import models
import time

class Organization(models.Model):
    name = models.CharField(max_length = 100)
    members = models.IntegerField(default = 0)
    website = models.CharField(max_length = 1000)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length = 250)
    time = models.CharField(max_length = 250)
    date = models.CharField(max_length = 250)
    event_description = models.CharField(default = '' ,max_length = 750)
    address = models.CharField(default = '' ,max_length = 750)
    picture_url = models.CharField(default = '' ,max_length = 1000)

    def __str__(self):
        return self.name

website/mainPage/views.py
from django.shortcuts import render
from .models import Organization, Event


# Create your views here.


def index(request):
    if request.method == 'POST':
        event = Event()
        event.name = request.POST.get('name')
        event.time = request.POST.get('time')
        event.date = request.POST.get('date')
        event.event_description = request.POST.get('event_description')
        event.address = request.POST.get('address')
        event.picture_url = request.POST.get('picture_url')
        if request.POST.get('picture_url') == '':
            event.picture_url = 'http://via.placeholder.com/120x120'
        event.save()
    organizations = Organization.objects.all()
    return render(request, 'mainPage/index.html', 
    {'organizations': sorted(organizations, key = lambda x: x.name)
    })


def events(request):
    events = Event.objects.all()
    return render(request, 'mainPage/events.html',{'events': sorted(events,key = lambda x: x.name)}
    )

website/mainPage/templates/base.html
<head>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<style>
    body{
        background-color: #F8F8F8;
        font-family: Helvetica;
    }
</style>
{% block head %}
{% endblock %}
</head>

<body>

<div class="container">

        <!-- Static navbar -->
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Givsum Test Website</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                {% block bar %}
                {% endblock %}
              </ul>
            </div><!--/.nav-collapse -->
          </div><!--/.container-fluid -->
        </nav>
  
      </div> <!-- /container -->
      {% block body %}
      {% endblock %}
</body>

website/mainPage/templates/mainPage/events.html
{% extends 'base.html' %}
{% block head %}
<meta charset="utf-8">
    <title>sample</title>

    <style>
    body {
        font-family: Helvetica;
    }
    .event {
        background-color: #efefef;
        padding: 20px 10px 10px 10px;
        margin: 10px auto;
        width: 60%;
        border-radius: 10px;
    }
    .event-left {
        width: 10%;
    }
    .event-right {
        width: 50%;
        margin-left: 190px;
        margin-top: -185px;
        margin-bottom: 20px;
    }
    #icon img {
        width: 120px;
        height: 120px;
        border-radius: 60px;
        margin-left: 30px;
        margin-bottom: 25px;
    }
    #time {
        margin-left: 50px;
        font-size: 30px;
        font-weight: bold;
    }
    .col-9 {
        margin-left: 55px;
        margin-top: 5px;
        margin-bottom: -5px;
    }
    #date {
        font-size: 20px;
        color: #323232;
        text-transform: uppercase;
        margin-bottom: -15px;
    }
    #event {
        font-size: 40px;
        font-weight: bold;
        text-transform: uppercase;        
    }
    #location {
        font-size: 20px;
        color: #323232;
        text-transform: uppercase;
        font-style: italic;
        margin-top: -15px;
    }
    #description {
        font-size: 12px;
        width: 575px;
        height: 70px;
        margin-bottom: 30px;
    }
    .information {
        position: relative;
        margin: -2px 0px 0px 0px;
    }
    </style>

{% endblock %}

{% block bar %}
    <li><a href="/">Home</a></li>
    <li class="active"><a href="/events/">Events Data</a></li>
{% endblock %}

{% block body %}
{% for event in events %}
<div class="event">
    <div class="event-left">
        <div id="time">{{event.time}}</div>
        <div id="icon"><img src={{event.picture_url}}></div>
    </div>
    <div class="event-right">
        <div class="information">
            <div id="date">{{event.date}}</div>
            <div id="event">{{event.name}}</div>
            <div id="location">{{event.address}}</div>
            <div id="description">{{event.event_description}}</div>
        </div>
    </div>
</div>
{% endfor %}



{% endblock %}

website/mainPage/templates/mainPage/index.html
{% extends 'base.html' %}
{% block head %}        
    <title>Sample Page</title>
    <style>
        body{
            font-family: Helvetica;
        }
        #box {
            width: 30%;
            height: 70%;
            min-height: 650px;
            margin: auto;
            background-color: #ff8c69;
            color: #ffffff;
            padding: 25px;
            border-radius: 5px;
            opacity: .9;
        }
        form {
            margin-top: 25px;
            color: white;
        }
        button{
            margin-top: 20px;
        }
        .btn-light {
            background-color: #ffffff;
            color: #ff8c69;
            font-weight: bold;
        }
        .btn-light:hover {
            color: #ffffff;
            background-color: #ff8c69;
            border: #fff 1px solid
        }

    </style>
{% endblock %}

{% block bar %}
<li class="active"><a href="/">Home</a></li>
<li><a href="/events/">Events Data</a></li>
{% endblock %}

{% block body %}

    <div id = box>
        <form action= {% url 'mainPage:index' %} method='post'>
            {% csrf_token %}
                <div class="form-group">
                <label for="email">Name:</label>
                <input class="form-control" id="email" name="name" placeholder="Enter event name">
                </div>
                <div class="form-group">
                <label for="email">Organization:</label>
                <input class="form-control" id="email" name="organization" placeholder="Enter organization name">
                </div>
                <div class="form-group">
                <label for="email">Time:</label>
                <input class="form-control" id="email" name="time" placeholder="Enter time">
                </div>
                <div class="form-group">
                <label for="email">Date:</label>
                <input class="form-control" id="email" name="date" placeholder="Enter date">
                </div>
                <div class="form-group">
                <label for="email">Event Description:</label>
                <input class="form-control" id="email" name="event_description" placeholder="Enter event description">
                </div>
                <div class="form-group">
                <label for="email">Address:</label>
                <input class="form-control" id="email" name="address" placeholder="Enter address">
                </div>
                <div class="form-group">
                <label for="email">Picture URL:</label>
                <input class="form-control" id="email" name="picture_url" placeholder="Enter picture url">
                </div>
                <button type="submit" class="btn btn-light">Submit</button>
            
        </form>

                
                
    </div>

{% endblock %}